name: cellem
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - h5py
  - mlflow
  - simpleitk
  - scikit-learn
  - pip:
    - albumentations
    - imagehash
    - segmentation-models-pytorch
